version: 0.2
phases:
  install:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging Lambda function...
artifacts:
  files:
    - '**/*'
