version: 0.2

phases:
  install:
    commands:
      - echo Installing Python packages...
  build:
    commands:
      - echo Building...
      - zip -r function.zip .
artifacts:
  files:
    - function.zip
