version: 0.2
phases:
  install:
    commands:
      - echo Installing source dependencies...
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging Lambda function...
artifacts:
  files:
    - '**/*'
